routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/locations/{city}', 'HomeController@getlocations');
Route::get('/vendors/{id}', 'HomeController@getvendors');
Route::get('/menu', "HomeController@showmenu");

Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin', 'AdminController@index');

Route::get('/login', 'Auth\UserLoginController@showLoginForm')->name('user.login');
Route::post('/login', 'Auth\UserLoginController@login')->name('user.login.submit');
Route::get('/seller',function(Request $req){
    return view('auth.seller');
});
Route::get('/register/oauth/callback/{token}/{email}/{name}','Auth\oauth@register');
Route::get('/logout', function(){
    Auth::logout();
    return redirect('/');
});

Route::get('/tiffin',function(){
    return view('tiffin');
});

Route::group(['middleware' => 'auth'], function() {
Route::get('/cart/increase/{id}','CartController@increase')->name('cart.increase');
Route::get('/cart/decrease/{id}', 'CartController@decrease')->name('cart.decrease');
Route::get('/cart/remove/{id}', 'CartController@remove')->name('cart.remove');
Route::get('/cart/add', 'CartController@add')->name('cart.add');

Route::get('/cart/thankyou', function(){
    return view('cart.thankyou');
})->name('cart.thankyou');
Route::resource('/cart', 'CartController');
});

Route::post('/register/seller','Auth\vendorAuth@Login');

Route::group(['middleware' => 'auth:admins'], function () {


    Route::get('/admin', function(){
        return view('admin.dashboard');
    });
    Route::get('admin/orderconfirm', 'OrderController@showconfirm');
    Route::get('admin/today', 'OrderController@showtoday');
    Route::get('admin/orderconfirm/{id}', 'OrderController@confirm')->name('order.confirm');
    Route::get('admin/cancel/{id}', 'OrderController@cancel')->name('order.cancel');
    Route::resource('admin/order', 'OrderController');

    Route::resource('admin/product', 'ProductController');
    Route::resource('admin/vendor', 'VendorController');

    Route::get('/admin/logout', function (){
        Auth::guard('admins')->logout();
        return redirect('/admin');
    });

    Route::get('password', 'OrderController@password');
	Route::post('password', 'OrderController@updatePassword');

	});

resources/views/home.blade.php
<!-- @extends('layouts.front')

@section('content') -->
@include('layouts.header');
@include('layouts.mid');


<div class="container-fluid bg-2" >
@include('layouts.category')
    <div class="alignment-container">
    @include('layouts.filter')

    <div class="vendor-container">

    </div>
    </div>

</div>


<script src="{{ asset('js/jquery-1.12.4.js') }}"></script>

<script type="text/javascript">
    $.ajaxSetup({
    headers: {
        'X-CSRF-Token': $('meta[name="_token"]').attr('content')
    }
    });
    var locations = {};
    var vendors = {};

    function getLocations(city){
        $.ajax({
            url : '/locations/'+city,
            type : 'GET',
            async: false,
            dataType : 'json',
            success : function(data){
                locations = data;
            }

        });
    }
    function getVendors(location){
        $.ajax({
            url : '/vendors/'+location,
            type : 'GET',
            async : false,
            dataType : 'json',
            success: function(data){
                vendors = data;
            }
        });
    }
    $(document).ready(function(){
//
        $('#city-select').on('change', function(){
            $('#location-select').html('<option value="0">Select Locality</option>')
            getLocations($('#city-select').val());
            $.each(locations, function(key, value){
                $('#location-select').append('<option value="'+value.id+'">'+value.name+'</option>');
            });
        });

        $('#filter-location').on('click', function(){
            $('.vendor-container').html('');
            getVendors($('#location-select').val());
            $.each(vendors, function(key, value){
                $('.vendor-container').append('<div class="container-fluid vendor thumbnail"><a href="/menu"><h3>'+value.name+'</h3> <h4>'+value.email+'</h4></a><h5>Rating :5.00</h5></div>');
            });
        });
    });
</script>


@include('layouts.footer')

resources/views/menu.blade.php
@extends('layouts.front')

@section('content')

<div class="container-fluid bg-2" >
    <div>
        <!-- Nav tabs -->
        <div class="menu-tab text-center" id="menu">
            <ul class="nav nav-tabs text-center" role="tablist">                                        
                <li role="presentation" class="sel active">
                    <a id="breakfast" aria-controls="home" role="tab" class="menuselection" data-cutoff="16:32:14" data-kitchen="1" data-id="breakfast" data-status="" data-dtime="" data-toggle="tab">BREAKFAST<i class="fa fa-check"></i></a>
                </li>                        
                <li role="presentation" class="sel">
                    <a id="lunch" aria-controls="home" role="tab" class="menuselection" data-cutoff="13:00:00" data-kitchen="1" data-id="lunch" data-status="" data-dtime="" data-toggle="tab">LUNCH<i class="fa fa-check" ></i></a>
                </li>                                    
                <li role="presentation" class="sel">
                    <a id="dinner" aria-controls="home" role="tab" class="menuselection" data-cutoff="20:00:00" data-kitchen="1" data-id="dinner" data-status="" data-dtime="" data-toggle="tab">DINNER<i class="fa fa-check"></i></a>
                </li>                
            </ul>                           
        </div>    
    </div>
    
    <div class="clearfix">
        <div class="pull-right  time ob" id="acceptance_time">PLACE ORDER FOR TOMORROW &amp; COMING DAYS.</div>
    </div>

    <hr>
    <div class="pull-left menu-head">MY MEAL CATEGORY</div>
    <hr>
    <hr>
    <div class="row bg-3">
        @foreach($products as $product)
            <div class="col-sm-4 col-lg-4 col-md-4 col-sm-6 col-sm-6 list-item Array">
                <div class = "thumbnail">
                     <img class = "img-rounded" src= "{{ asset('images/'.$product->image) }}">
                     <hr style=" width:200px;color:black; border-top:1px solid black; border-bottom:1px solid   ;">
                     <div  class="caption">
                        <h4 class="text-center" style="min-height:0px;">{{$product->name}}</h4>
                        <div class="clearfix">
                            <div class="pull-left">
                                <label class="">Rs&nbsp;{{$product->price}}</label>
                            </div>
                            <div class="pull-right">
                                <p>
                                    
                                    
                                    <a href="{{route('cart.edit', $product->id)}}" class="add-to-cart">ADD</a>
                                </p>
                            </div>
                        </div>
                        <div class = "text-center">
                            <div class="center">
                                <a href="{{'#'.$product->id}}" data-toggle ="modal" class="view">View Items</a>
                            </div>
                        </div>
                     </div>
                </div>
            </div>
            <div id="{{$product->id}}" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="monthTitle">View Items
                                <button type="button" class="close" style="display: block !important" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">x</span>
                                </button>
                            </h4>               
                        </div>
                        <div class="modal-body">
                            <p>{{ $product->description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach    
    </div>
</div>

@endsection

resources/views/password.blade.php
@extends('layouts.app')

@section('title')
    Change Password
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Workset</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Add a Order</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Add Order
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>

            <div class="panel-body">

                {!! Form::open(array('method'=>'POST')) !!}
                    <div class="col-sm-6">

                        @if($errors)
                            @foreach ($errors->all() as $error)
                                <div class="alert alert-danger">{{ $error }}</div>
                            @endforeach
                        @endif

                        <div class="form-group">
                            <label>Current Password</label>
                            {!! Form::password('mypassword', ['placeholder'=>'Enter Current Password', 'class'=>'form-control input-lg']) !!}
                        </div>
                        <br>
                        <div class="form-group">
                            <label>New Password</label>
                            {!! Form::password('password', ['placeholder'=>'Enter New Password', 'class'=>'form-control input-lg']) !!}
                            <span class="pull-right"><i>Password length minimum 6 and maximum 18 </i></span>
                        </div>
                        <div class="form-group">
                            <label>Confirm Password</label>
                            {!! Form::password('password_confirmation', ['placeholder'=>'Confirm Password', 'class'=>'form-control input-lg']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <img src="{{ asset('images/lock.jpg') }}" width="80%" class="pull-right">
                    </div>
                    <div class="col-md-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        {!! Form::submit('Submit', [ 'class'=>'btn btn-default']) !!}
                    </div>
                {!! Form::close() !!}
            </div>

        </section>
    </section>
</section>

@endsection

resources/views/tiffin.blade.php
@include('layouts.header');
<style>
    #detectme{
        margin : 6em auto;
    }
</style>
<div class="alignment-container">
    <button id="detectme">
    detect
    </button>

</div>
<script>

</script>
@include('layouts.footer');