routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/locations/{city}', 'HomeController@getlocations');
Route::get('/vendors/{id}', 'HomeController@getvendors');
Route::get('/menu', "HomeController@showmenu");

Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin', 'AdminController@index');

Route::get('/login', 'Auth\UserLoginController@showLoginForm')->name('user.login');
Route::post('/login', 'Auth\UserLoginController@login')->name('user.login.submit');
Route::get('/seller',function(Request $req){
    return view('auth.seller');
});
Route::get('/register/oauth/callback/{token}/{email}/{name}','Auth\oauth@register');
Route::get('/logout', function(){
    Auth::logout();
    return redirect('/');
});

Route::get('/tiffin',function(){
    return view('tiffin');
});

Route::group(['middleware' => 'auth'], function() {
Route::get('/cart/increase/{id}','CartController@increase')->name('cart.increase');
Route::get('/cart/decrease/{id}', 'CartController@decrease')->name('cart.decrease');
Route::get('/cart/remove/{id}', 'CartController@remove')->name('cart.remove');
Route::get('/cart/add', 'CartController@add')->name('cart.add');

Route::get('/cart/thankyou', function(){
    return view('cart.thankyou');
})->name('cart.thankyou');
Route::resource('/cart', 'CartController');
});

Route::post('/register/seller','Auth\vendorAuth@Login');

Route::group(['middleware' => 'auth:admins'], function () {


    Route::get('/admin', function(){
        return view('admin.dashboard');
    });
    Route::get('admin/orderconfirm', 'OrderController@showconfirm');
    Route::get('admin/today', 'OrderController@showtoday');
    Route::get('admin/orderconfirm/{id}', 'OrderController@confirm')->name('order.confirm');
    Route::get('admin/cancel/{id}', 'OrderController@cancel')->name('order.cancel');
    Route::resource('admin/order', 'OrderController');

    Route::resource('admin/product', 'ProductController');
    Route::resource('admin/vendor', 'VendorController');

    Route::get('/admin/logout', function (){
        Auth::guard('admins')->logout();
        return redirect('/admin');
    });

    Route::get('password', 'OrderController@password');
	Route::post('password', 'OrderController@updatePassword');

	});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
	protected $fillable = ['name', 'phone', 'address', 'delivery_date', 'product_id', 'payment_option', 'quantity', 'order_status'];
    public function product(){
        return $this->belongsTo('App\Product');
    }
}

resources/views/admin/order/dispatch.blade.php
@extends('layouts.app')

@section('title')
    All Orders
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Dispatch Orders</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Dispatch Orders</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Prepared Food
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="prepared-food">
                @foreach($orders as $order)
                    
                @endforeach
            </div>
            
        </section>
    </section>
 </section>

@endsection

resources/views/admin/order/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Order
@endsection


@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Workset</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Add a Order</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Add Order
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>

            <div class="panel-body">
                {!! Form::model($order, array('method'=>'PATCH','route' => array('order.update', $order->id))) !!}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Name</label>
                            {!! Form::text('name', null, ['placeholder'=>'Enter full name', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            {!! Form::text('phone', null, ['placeholder'=>'Enter phone number', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            {!! Form::textarea('address', null, ['placeholder'=>'Enter full address', 'class'=>'form-control input-lg','rows'=>'3','required']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Delivery Date</label>
                            {!! Form::date('delivery_date', null, [ 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Product ID</label>
                            {!! Form::select('product_id', $product, null, ['id'=>'product_id', 'class'=>'form-control m-b input-lg','required']) !!}
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Select Pament Option</label>
                                    {!! Form::select('payment_option', array( 'Postpay' => 'Postpay', 'Prepay (Full)' => 'Prepay (full)', 'Prepay (Half)' => 'Prepay (Half)'), null, ['class'=>'form-control m-b input-lg','required']) !!}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Quantity</label>
                                    {!! Form::number('quantity', null, ['placeholder'=>'Enter quantity', 'class'=>'form-control input-lg','required']) !!}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        <div class="row">
                            <div class="form-group">
                                <label class="col-sm-2">Status</label>
                                <div class="col-sm-10 ">
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Confirm') !!}<i class="fa fa-circle-o fa-1x"></i>Confirm </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Ready') !!}<i class="fa fa-circle-o"></i>Item Ready </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Send') !!}<i class="fa fa-circle-o"></i>Send </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Delivered') !!}<i class="fa fa-circle-o"></i>Delivered </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Returned') !!}<i class="fa fa-circle-o"></i>Returned </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Cancelled') !!}<i class="fa fa-circle-o"></i>Cancelled </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        {!! Form::submit('Submit', [ 'class'=>'btn btn-default']) !!}
                    </div>
                {!! Form::close() !!}
            </div>

        </section>
    </section>
</section>

@endsection

resources/views/admin/order/index.blade.php
@extends('layouts.app')

@section('title')
    All Orders
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">All Orders</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Orders Data</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                All Orders Data
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables" id="table">
                    <thead>
                        <tr>
                            <th width="">Bill No.</th>
                            <th width="">Customer</th>
                            <th width="">Location</th>
                            <th width="">Amount</th>
                            <th width="">Meal</th>
                            <th width="">Payment</th>
                            <th width="">Status</th>
                            <th width="">Menu</th>
                            <th width="">Delivery</th>
                            <th width="">Date</th>
                            
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order )
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>
                                <td>{{ $order->address }}</td>
                                <td>{{ $order->product->price * $order->quantity }}</td>
                                <td>{{ $order->product->name }}({{$order->quantity}})</td>
                                <td>{{ $order->payment_option }}</td>
                                <td>{{ $order->order_status }}</td>
                                <td> Breakfast</td>
                                <td>
                                    @if($order->status == 'Delivered')
                                        Delivered
                                    @else
                                        Pending
                                    @endif
                                </td>
                                <td>{{ $order->delivery_date}}</td>
                                
                                
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </section>
 </section>

@endsection

resources/views/admin/order/new.blade.php
@extends('layouts.app')

@section('title')
    Add Order
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="index.html"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Workset</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Add a Order</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                Add Order
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>

            <div class="panel-body">
                {!! Form::open(array('route'=>'order.store')) !!}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Name</label>
                            {!! Form::text('name', '', ['placeholder'=>'Enter full name', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            {!! Form::text('phone', '', ['placeholder'=>'Enter phone number', 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            {!! Form::textarea('address', '', ['placeholder'=>'Enter full address', 'class'=>'form-control input-lg','rows'=>'3','required']) !!}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Delivery Date</label>
                            {!! Form::date('delivery_date', '', [ 'class'=>'form-control input-lg','required']) !!}
                        </div>
                        <div class="form-group">
                            <label>Product ID</label>
                            {!! Form::select('product_id', $product, null, ['id'=>'product_id', 'class'=>'form-control m-b input-lg','required']) !!}
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Select Pament Option</label>
                                    {!! Form::select('payment_option', array( 'Postpay' => 'Postpay', 'Prepay (Full)' => 'Prepay (full)', 'Prepay (Half)' => 'Prepay (Half)'), null, ['class'=>'form-control m-b input-lg','required']) !!}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Quantity</label>
                                    {!! Form::number('quantity', '1', ['placeholder'=>'Enter quantity', 'class'=>'form-control input-lg', 'required']) !!}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        <div class="row">
                            <div class="form-group">
                                <label class="col-sm-2">Status</label>
                                <div class="col-sm-10 ">
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Confirm') !!}<i class="fa fa-circle-o fa-1x"></i>Confirm </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Ready') !!}<i class="fa fa-circle-o"></i>Item Ready </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Send') !!}<i class="fa fa-circle-o"></i>Send </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Delivered') !!}<i class="fa fa-circle-o"></i>Delivered </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Returned') !!}<i class="fa fa-circle-o"></i>Returned </label>
                                    <label class="radio-custom col-md-2 input-md">{!! Form::radio('order_status', 'Cancelled') !!}<i class="fa fa-circle-o"></i>Cancelled </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="line line-dashed line-lg pull-in"></div>
                        {!! Form::submit('Submit', [ 'class'=>'btn btn-default']) !!}
                    </div>
                {!! Form::close() !!}
            </div>

        </section>
    </section>
</section>

@endsection

resources/views/admin/order/orderconfirm.blade.php
@extends('layouts.app')

@section('title')
    Confirm Orders
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Confirm Orders</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Orders Data</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                All Orders Data
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables" id="table">
                    <thead>
                        <tr>
                            <th width="">Sr. No.</th>
                            <th width="">Name</th>
                            <th width="">Phone</th>
                            <!-- <th width="">Email</th> -->
                            <th width="">Delivery Date</th>
                            <th width="">Meal</th>
                            <th width="">Amount</th>
                            <th width="">Payment</th>
                            <th width="">Status</th>
                            <th width="150px">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order )
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>
                                <td>{{ $order->mobile }}</td>
                                <!-- <td>{{ $order->email }}</td> -->
                                <td>{{ $order->delivery_date }}</td>
                                <td>{{ $order->product->name }}</td>
                                <td><i class="fa fa-inr"></i>&nbsp;{{ $order->product->price * $order->quantity }}</td>
                                <td>{{ $order->payment_option }}</td>
                                <td>
                                    @if($order->order_status == 'Unconfirmed')
                                        pending
                                    @else
                                        success
                                    @endif
                                </td>
                                @if($order->order_status == 'Unconfirmed')
                                    <!-- <td class="text-success"><b style="border: 1px solid; padding: 2px 5px"><a href="{{route('order.confirm', $order->id)}}">{{ $order->order_status }}</a></b></td> -->
                                <td><a href="{{ route('order.confirm',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-edit"></i></a></td>

                                
                                @else
                                    <td>--</td>
                                @endif
                                <!-- <td>
                                    {{ Form::open(['route' => ['order.destroy', $order->id], 'method' => 'delete', 'style'=>'display:inline-block']) }}
                                    <button type="submit" class="btn btn-sm btn-icon btn-danger" onclick="return confirm('Are you sure you want to delete this?')" ><i class="fa fa-trash-o"></i></button>
                                    {{ Form::close() }}
                                    <a href="{{ route('order.edit',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{{ route('order.show',$order->id) }}" class="btn btn-sm btn-icon btn-success"><i class="fa fa-print"></i></a>
                                </td> -->
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </section>
 </section>

@endsection

resources/views/admin/order/ref.blade.php
@extends('layouts.app')

@section('title')
    Confirm Orders
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Confirm Orders</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Orders Data</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                All Orders Data
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables" id="table">
                    <thead>
                        <tr>
                            <th width="">Sr. No.</th>
                            <th width="">Name</th>
                            <th width="">Phone</th>
                            <!-- <th width="">Email</th> -->
                            <th width="">Delivery Date</th>
                            <th width="">Meal</th>
                            <th width="">Amount</th>
                            <th width="">Payment</th>
                            <th width="">Status</th>
                            <th width="150px">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order )
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>
                                <td>{{ $order->mobile }}</td>
                                <!-- <td>{{ $order->email }}</td> -->
                                <td>{{ $order->delivery_date }}</td>
                                <td>{{ $order->product->name }}</td>
                                <td>{{ $order->product->price * $order->quantity }}</td>
                                <td>{{ $order->payment_option }}</td>
                                <td>{{ $order->order_status }}</td>
                                @if($order->order_status == 'Unconfirmed')
                                    <td class="text-success"><b style="border: 1px solid; padding: 2px 5px">{{ $order->order_status }}</b></td>
                                @else
                                    <td>--</td>
                                @endif
                                <td>
                                    {{ Form::open(['route' => ['order.destroy', $order->id], 'method' => 'delete', 'style'=>'display:inline-block']) }}
                                    <button type="submit" class="btn btn-sm btn-icon btn-danger" onclick="return confirm('Are you sure you want to delete this?')" ><i class="fa fa-trash-o"></i></button>
                                    {{ Form::close() }}
                                    <a href="{{ route('order.edit',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{{ route('order.show',$order->id) }}" class="btn btn-sm btn-icon btn-success"><i class="fa fa-print"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </section>
 </section>

@endsection

resources/views/admin/order/today.blade.php
@extends('layouts.app')

@section('title')
    Confirm Orders
@endsection

@section('body')

<section class="vbox">
    <section class="scrollable padder">
        <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
            <li><a href="{{url('/')}}"><i class="fa fa-home"></i> Home</a></li>
            <li class="active">Today's Orders</li>
        </ul>
        <div class="m-b-md">
            <h3 class="m-b-none">Orders Data</h3>
        </div>
        <section class="panel panel-default">
            <header class="panel-heading">
                All Orders Data
                <i class="fa fa-info-sign text-muted" data-toggle="tooltip" data-placement="bottom" data-title="ajax to load the data."></i>
            </header>
            <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables" id="table">
                    <thead>
                        <tr>
                            <th width="">Bill. No.</th>
                            <th width="">Customer</th>
                            <th width="">Location</th>
                            <!-- <th width="">Email</th> -->
                            <th width="">Amount</th>
                            <th width="">Meal</th>
                            <th width="">Payment</th>
                            <th width="">Menu</th>
                            <th width="">Delivery</th>
                            <th width="">Date</th>
                            <th width="">Delivery Person</th>
                            <th width="150px">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($orders as $order )
                            <tr>
                                <td><i class="fa fa-bullet"></i>&nbsp;{{ $order->id }}</td>
                                <td>{{ $order->name }}</td>
                                <td>{{ $order->address }}</td>
                                <td><i class="fa fa-inr"></i>&nbsp;{{ $order->product->price * $order->quantity }}</td>
                                <td>{{ $order->product->name }}({{ $order->quantity }})</td>

                                <td>{{ $order->payment_option }}</td>
                                <td>Breakfast</td>
                                <td>
                                    @if($order->order_status == 'Dispatched')
                                        Dispatched
                                    @elseif($order->order_status == 'Delivered')
                                        Delivered
                                    @else
                                        Pending
                                    @endif
                                </td>
                                <td>{{ $order->delivery_date }}</td>
                                <td><select>
                                    <option>Delivery Person</option>
                                </select></td>
                            
                                @if($order->order_status == 'Confirmed')
                                    <!-- <td class="text-success"><b style="border: 1px solid; padding: 2px 5px"><a href="{{route('order.confirm', $order->id)}}">{{ $order->order_status }}</a></b></td> -->
                                <td><a href="{{ route('order.cancel',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-ban"></i></a></td>

                                @elseif($order->order_status == 'Dispatched')    
                                <td><a href="{{ route('order.cancel',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-thumbs-down"></i></a>
                                    <a href="{{ route('order.cancel',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-undo"></i></a>
                                </td>

                                @else
                                    <td></td>
                                @endif
                                <!-- <td>
                                    {{ Form::open(['route' => ['order.destroy', $order->id], 'method' => 'delete', 'style'=>'display:inline-block']) }}
                                    <button type="submit" class="btn btn-sm btn-icon btn-danger" onclick="return confirm('Are you sure you want to delete this?')" ><i class="fa fa-trash-o"></i></button>
                                    {{ Form::close() }}
                                    <a href="{{ route('order.edit',$order->id) }}" class="btn btn-sm btn-icon btn-warning"><i class="fa fa-edit"></i></a>
                                    <a href="{{ route('order.show',$order->id) }}" class="btn btn-sm btn-icon btn-success"><i class="fa fa-print"></i></a>
                                </td> -->
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </section>
 </section>

@endsection